export const FETCH_COUNTRIES_REQUEST =
  'ENTITIES/COUNTRIES/FETCH_COUNTRIES_REQUEST';
export const FETCH_COUNTRIES_SUCCESS =
  'ENTITIES/COUNTRIES/FETCH_COUNTRIES_SUCCESS';
export const FETCH_COUNTRIES_FAILURE =
  'ENTITIES/COUNTRIES/FETCH_COUNTRIES_FAILURE';
