export * from './background';
export * from './common';
export * from './icon';
export * from './policy';
export * from './screenshots';
export * from './smartphone';
export * from './social';
export * from './store';
export * from './text';
