export const FETCH_PROFILE_REQUEST = 'SERVICES/SESSION/FETCH_PROFILE_REQUEST';
export const FETCH_PROFILE_SUCCESS = 'SERVICES/SESSION/FETCH_PROFILE_SUCCESS';
export const FETCH_PROFILE_FAILURE = 'SERVICES/SESSION/FETCH_PROFILE_FAILURE';

export const LOGOUT = 'SERVICES/SESSION/LOGOUT';

export const SET_PRO = 'SERVICES/SESSION/SET_PRO';
export const SET_USER = 'SERVICES/SESSION/SET_USER';
export const SET_SUBSCRIPTION = 'SERVICES/SESSION/SET_SUBSCRIPTION';
