export const FETCH_WEBSITES_REQUEST = 'ENTITIES/WEBSITES/FETCH_WEBSITES_REQUEST';
export const FETCH_WEBSITES_SUCCESS = 'ENTITIES/WEBSITES/FETCH_WEBSITES_SUCCESS';
export const FETCH_WEBSITES_FAILURE = 'ENTITIES/WEBSITES/FETCH_WEBSITES_FAILURE';

export const SET_TEMPLATE_ID = 'ENTITIES/WEBSITES/SET_TEMPLATE_ID';

export const UPDATE_WEBSITE = 'ENTITIES/WEBSITES/UPDATE_WEBSITE';
export const UPDATE_WEBSITE_SECTION = 'ENTITIES/WEBSITES/UPDATE_WEBSITE_SECTION';
