export const FETCH_WEBSITES_REQUEST = 'ENTITIES/WEBSITES/FETCH_WEBSITES_REQUEST';
export const FETCH_WEBSITES_SUCCESS = 'ENTITIES/WEBSITES/FETCH_WEBSITES_SUCCESS';
export const FETCH_WEBSITES_FAILURE = 'ENTITIES/WEBSITES/FETCH_WEBSITES_FAILURE';
