// Entities
import {
  SMARTPHONE_MOCKUP,
  SMARTPHONE_MODEL,
  SMARTPHONE_STYLE,
} from 'entities/template/constants';

export const MOCKUP_ITEMS = {
  [SMARTPHONE_MODEL.IPHONE]: {
    [SMARTPHONE_STYLE.CLASSIC]: [
      SMARTPHONE_MOCKUP.CLASSIC_IPHONE_SILVER,
      SMARTPHONE_MOCKUP.CLASSIC_IPHONE_GRAY,
      SMARTPHONE_MOCKUP.CLASSIC_IPHONE_GOLD,
    ],
    [SMARTPHONE_STYLE.CONCEPT]: [
      SMARTPHONE_MOCKUP.CONCEPT_IPHONE_SILVER_GLASS,
      SMARTPHONE_MOCKUP.CONCEPT_IPHONE_SILVER_LINE,
      SMARTPHONE_MOCKUP.CONCEPT_IPHONE_GRAY_GLASS,
      SMARTPHONE_MOCKUP.CONCEPT_IPHONE_GRAY_LINE,
      SMARTPHONE_MOCKUP.CONCEPT_IPHONE_GOLD_GLASS,
      SMARTPHONE_MOCKUP.CONCEPT_IPHONE_GOLD_LINE,
    ],
    [SMARTPHONE_STYLE.FLAT]: [
      SMARTPHONE_MOCKUP.FLAT_IPHONE_SILVER,
      SMARTPHONE_MOCKUP.FLAT_IPHONE_GRAY,
      SMARTPHONE_MOCKUP.FLAT_IPHONE_GOLD,
    ],
  },
};
